name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: butlerlogic/action-autotag@stable
        env:
          GITHUB_TOKEN: ${{ github.token }}
